package dev.wildilde.car_stereo_wiki.api;

import dev.wildilde.car_stereo_wiki.entity.Tag;
import dev.wildilde.car_stereo_wiki.repository.TagRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;

@RestController
@RequestMapping
public class TagRestController {
    private final TagRepository tagRepository;

    public TagRestController(TagRepository tagRepository) {
        this.tagRepository = tagRepository;
    }

    @PostMapping("/api/tag/add")
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    public ResponseEntity<Tag> addTag(@RequestBody Tag tag) {
        // Tag.id is auto-generated by @GeneratedValue, so we don't need to provide it.
        Tag saved = tagRepository.save(tag);
        return ResponseEntity.created(URI.create("/api/tag/" + saved.getId())).body(saved);
    }
}
