spring.application.name=car_stereo_wiki
spring.devtools.livereload.enabled=true
logging.level.org.springframework.security=TRACE

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/car_stereo_wiki}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# GITHUB OAUTH
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:YOUR_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:YOUR_GITHUB_CLIENT_SECRET}