package dev.wildilde.car_stereo_wiki.web;

import dev.wildilde.car_stereo_wiki.entity.Tag;
import dev.wildilde.car_stereo_wiki.repository.TagRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import java.net.URI;

@Controller
public class TagController {
    private final TagRepository tagRepository;

    public TagController(TagRepository tagRepository) {
        this.tagRepository = tagRepository;
    }

    @GetMapping("/tag/add")
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    public String addTagForm(Model model) {
        model.addAttribute("tag", new Tag());
        return "page/tagAdd";
    }

    @PostMapping("/api/tag/add")
    @PreAuthorize("hasAuthority('ROLE_ADMIN')")
    public ResponseEntity<Void> addTag(@RequestBody Tag tag) {
        // Tag.id is auto-generated by @GeneratedValue, so we don't need to provide it.
        tagRepository.save(tag);
        return ResponseEntity.ok().build();
    }
}
